packages:
  - playground
  - client
  - examples/minimal

catalog:
  '@nuxt/devtools': 3.2.1
  '@nuxt/devtools-kit': 3.2.1
  '@nuxt/devtools-ui-kit': 3.2.1
  '@nuxt/eslint-config': ^1.15.1
  '@nuxt/kit': 4.3.1
  '@nuxt/module-builder': 1.0.2
  '@nuxt/schema': 4.3.1
  '@nuxt/test-utils': ^4.0.0
  '@tanstack/vue-query': ^5.92.9
  '@types/node': ^25.2.3
  '@unocss/nuxt': 66.6.0
  changelogen: ^0.6.2
  concurrently: ^9.2.1
  defu: ^6.1.4
  eslint: ^10.0.0
  nuxt: 4.3.1
  pkg-types: ^2.3.0
  sirv: ^3.0.2
  splitpanes: ^4.0.4
  typescript: ~5.9.3
  vitest: ^4.0.18
  vue: ^3.5.26
  vue-json-pretty: ^2.6.0
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
