packages:
  - playground
  - client
  - examples/minimal

minimumReleaseAge: 1440

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

catalog:
  "@nuxt/devtools": ^3.4.2
  "@nuxt/devtools-kit": ^3.4.2
  "@nuxt/eslint-config": ^1.17.0
  "@nuxt/kit": ^4.6.1
  "@nuxt/module-builder": 1.0.3
  "@nuxt/schema": ^4.6.1
  "@nuxt/test-utils": ^4.3.3
  "@tanstack/vue-query": ^5.104.1
  "@types/node": ^25.9.9
  "@unocss/nuxt": 66.10.5
  "@unocss/preset-icons": 66.10.5
  "@iconify-json/carbon": 1.2.28
  changelogen: ^0.6.2
  concurrently: ^10.0.6
  defu: ^6.1.7
  eslint: ^10.12.0
  nuxt: ^4.6.1
  pkg-types: ^2.3.3
  sirv: ^3.0.2
  splitpanes: ^4.0.4
  typescript: ~6.0.3
  vitest: ^4.1.11
  vue: ^3.5.26
  vue-json-pretty: ^2.5.0
  vue-router: ^5.0.2
  vue-tsc: ^3.3.12
  playwright-core: ^1.64.0

minimumReleaseAgeExclude:
  - nuxt
  - "@nuxt/*"
